---

- name: Test role with README example
  hosts: '{{ target | default("all") }}'
  vars:
    delta_version: 0.18.2
    jq_version: 1.8.1
    task_version: 3.44.1
    tool_deploy_list: >-
      {{ tool_deploy_default_config_delta
         | combine(tool_deploy_default_config_jq)
         | combine(tool_deploy_default_config_task) }}
  roles:
    - role: tool_deploy
  tags:
    - tools
    - readme

- name: Test role with bat
  hosts: '{{ target | default("all") }}'
  vars:
    bat_version: 0.25.0
    tool_deploy_list: "{{ tool_deploy_default_config_bat }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - bat

- name: Test role with delta
  hosts: '{{ target | default("all") }}'
  vars:
    delta_version: 0.18.2
    tool_deploy_list: "{{ tool_deploy_default_config_delta }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - delta

- name: Test role with direnv
  hosts: '{{ target | default("all") }}'
  vars:
    direnv_version: 2.37.1
    tool_deploy_list: "{{ tool_deploy_default_config_direnv }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - direnv

- name: Test role with dive
  hosts: '{{ target | default("all") }}'
  vars:
    dive_version: 0.13.1
    tool_deploy_list: "{{ tool_deploy_default_config_dive }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - dive

- name: Test role with docker-credential-pass
  hosts: '{{ target | default("all") }}'
  vars:
    docker_credential_version: 0.9.3
    tool_deploy_list: "{{ tool_deploy_default_config_docker_credential_pass }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - docker-credential-pass

- name: Test role with eza
  hosts: '{{ target | default("all") }}'
  vars:
    eza_version: 0.23.0
    tool_deploy_list: "{{ tool_deploy_default_config_eza }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - eza

- name: Test role with fd
  hosts: '{{ target | default("all") }}'
  vars:
    fd_version: 10.2.0
    tool_deploy_list: "{{ tool_deploy_default_config_fd }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - fd

- name: Test role with fx
  hosts: '{{ target | default("all") }}'
  vars:
    fx_version: 38.0.0
    tool_deploy_list: "{{ tool_deploy_default_config_fx }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - fx

- name: Test role with fzf
  hosts: '{{ target | default("all") }}'
  vars:
    fzf_version: 0.65.0
    tool_deploy_list: "{{ tool_deploy_default_config_fzf }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - fzf

- name: Test role with glow
  hosts: '{{ target | default("all") }}'
  vars:
    glow_version: 2.1.0
    tool_deploy_list: "{{ tool_deploy_default_config_glow }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - glow

- name: Test role with gopass
  hosts: '{{ target | default("all") }}'
  vars:
    gopass_version: 1.15.16
    tool_deploy_list: "{{ tool_deploy_default_config_gopass }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - gopass

- name: Test role with gopass-jsonapi
  hosts: '{{ target | default("all") }}'
  vars:
    gopass_jsonapi_version: 1.15.16
    tool_deploy_list: "{{ tool_deploy_default_config_gopass_jsonapi }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - gopass-jsonapi

- name: Test role with gum
  hosts: '{{ target | default("all") }}'
  vars:
    gum_version: 0.16.0
    tool_deploy_list: "{{ tool_deploy_default_config_gum }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - gum

- name: Test role with hadolint
  hosts: '{{ target | default("all") }}'
  vars:
    hadolint_version: 2.12.0
    tool_deploy_list: "{{ tool_deploy_default_config_hadolint }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - hadolint

- name: Test role with hexyl
  hosts: '{{ target | default("all") }}'
  vars:
    hexyl_version: 0.16.0
    tool_deploy_list: "{{ tool_deploy_default_config_hexyl }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - hexyl

- name: Test role with hyperfine
  hosts: '{{ target | default("all") }}'
  vars:
    hyperfine_version: 1.19.0
    tool_deploy_list: "{{ tool_deploy_default_config_hyperfine }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - hyperfine

- name: Test role with jq
  hosts: '{{ target | default("all") }}'
  vars:
    jq_version: 1.8.1
    tool_deploy_list: "{{ tool_deploy_default_config_jq }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - jq

- name: Test role with keepassxc
  hosts: '{{ target | default("all") }}'
  vars:
    keepassxc_version: 2.7.9
    tool_deploy_list: "{{ tool_deploy_default_config_keepassxc }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - keepassxc

- name: Test role with kubectl
  hosts: '{{ target | default("all") }}'
  vars:
    kubectl_version: 1.32.2
    tool_deploy_list: "{{ tool_deploy_default_config_kubectl }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - kubectl

- name: Test role with lazydocker
  hosts: '{{ target | default("all") }}'
  vars:
    lazydocker_version: 0.24.1
    tool_deploy_list: "{{ tool_deploy_default_config_lazydocker }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - lazydocker

- name: Test role with lazygit
  hosts: '{{ target | default("all") }}'
  vars:
    lazygit_version: 0.50.0
    tool_deploy_list: "{{ tool_deploy_default_config_lazygit }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - lazygit

- name: Test role with less
  hosts: '{{ target | default("all") }}'
  vars:
    less_version: 668
    tool_deploy_list: "{{ tool_deploy_default_config_less }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - less

- name: Test role with lsd
  hosts: '{{ target | default("all") }}'
  vars:
    lsd_version: 1.1.5
    tool_deploy_list: "{{ tool_deploy_default_config_lsd }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - lsd

- name: Test role with micro
  hosts: '{{ target | default("all") }}'
  vars:
    micro_version: 2.0.14
    tool_deploy_list: "{{ tool_deploy_default_config_micro }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - micro

- name: Test role with minikube
  hosts: '{{ target | default("all") }}'
  vars:
    minikube_version: 1.35.0
    tool_deploy_list: "{{ tool_deploy_default_config_minikube }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - minikube

- name: Test role with moar
  hosts: '{{ target | default("all") }}'
  vars:
    moar_version: 1.35.5
    tool_deploy_list: "{{ tool_deploy_default_config_moar }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - moar

- name: Test role with nnn
  hosts: '{{ target | default("all") }}'
  vars:
    nnn_version: 5.1
    tool_deploy_list: "{{ tool_deploy_default_config_nnn }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - nnn

- name: Test role with nvim
  hosts: '{{ target | default("all") }}'
  vars:
    nvim_version: 0.11.1
    tool_deploy_list: "{{ tool_deploy_default_config_nvim }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - nvim

- name: Test role with oh-my-posh
  hosts: '{{ target | default("all") }}'
  vars:
    oh_my_posh_version: 26.17.0
    tool_deploy_list: "{{ tool_deploy_default_config_oh_my_posh }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - oh-my-posh

- name: Test role with pet
  hosts: '{{ target | default("all") }}'
  vars:
    pet_version: 1.0.1
    tool_deploy_list: "{{ tool_deploy_default_config_pet }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - pet

- name: Test role with restic
  hosts: '{{ target | default("all") }}'
  vars:
    restic_version: 0.18.0
    tool_deploy_list: "{{ tool_deploy_default_config_restic }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - restic

- name: Test role with rg
  hosts: '{{ target | default("all") }}'
  vars:
    rg_version: 14.1.1
    tool_deploy_list: "{{ tool_deploy_default_config_rg }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - rg

- name: Test role with sqlitebrowser
  hosts: '{{ target | default("all") }}'
  vars:
    sqlitebrowser_version: 3.13.1
    tool_deploy_list: "{{ tool_deploy_default_config_sqlitebrowser }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - sqlitebrowser

- name: Test role with talosctl
  hosts: '{{ target | default("all") }}'
  vars:
    talosctl_version: 1.9.4
    tool_deploy_list: "{{ tool_deploy_default_config_talosctl }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - talosctl

- name: Test role with task
  hosts: '{{ target | default("all") }}'
  vars:
    task_version: 3.44.1
    tool_deploy_list: "{{ tool_deploy_default_config_task }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - task

- name: Test role with tealdeer
  hosts: '{{ target | default("all") }}'
  vars:
    tealdeer_version: 1.7.2
    tool_deploy_list: "{{ tool_deploy_default_config_tealdeer }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - tealdeer

- name: Test role with tig
  hosts: '{{ target | default("all") }}'
  vars:
    tig_version: 2.5.12
    tool_deploy_list: "{{ tool_deploy_default_config_tig }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - tig

- name: Test role with tmux
  hosts: '{{ target | default("all") }}'
  vars:
    tmux_version: 3.5a
    tool_deploy_list: "{{ tool_deploy_default_config_tmux }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - tmux

- name: Test role with uv
  hosts: '{{ target | default("all") }}'
  vars:
    uv_version: 0.7.2
    tool_deploy_list: "{{ tool_deploy_default_config_uv }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - uv

- name: Test role with vhs
  hosts: '{{ target | default("all") }}'
  vars:
    vhs_version: 0.9.0
    tool_deploy_list: "{{ tool_deploy_default_config_vhs }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - vhs

- name: Test role with xh
  hosts: '{{ target | default("all") }}'
  vars:
    xh_version: 0.24.1
    tool_deploy_list: "{{ tool_deploy_default_config_xh }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - xh

- name: Test role with xq
  hosts: '{{ target | default("all") }}'
  vars:
    xq_version: 1.3.0
    tool_deploy_list: "{{ tool_deploy_default_config_xq }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - xq

- name: Test role with yq
  hosts: '{{ target | default("all") }}'
  vars:
    yq_version: 4.45.2
    tool_deploy_list: "{{ tool_deploy_default_config_yq }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - yq

- name: Test role with zoxide
  hosts: '{{ target | default("all") }}'
  vars:
    zoxide_version: 0.9.7
    tool_deploy_list: "{{ tool_deploy_default_config_zoxide }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - zoxide

...
