---

- name: Test role with README example
  hosts: '{{ target | default("all") }}'
  vars:
    delta_version: 0.18.2
    jq_version: 1.7.1
    task_version: 3.40.1
    tool_deploy_list: >-
      {{ tool_deploy_default_config_delta
         | combine(tool_deploy_default_config_jq)
         | combine(tool_deploy_default_config_task) }}
  roles:
    - role: tool_deploy
  tags:
    - tools
    - readme

- name: Test role with bat
  hosts: '{{ target | default("all") }}'
  vars:
    bat_version: 0.25.0
    tool_deploy_list: "{{ tool_deploy_default_config_bat }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - bat

- name: Test role with delta
  hosts: '{{ target | default("all") }}'
  vars:
    delta_version: 0.18.2
    tool_deploy_list: "{{ tool_deploy_default_config_delta }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - delta

- name: Test role with direnv
  hosts: '{{ target | default("all") }}'
  vars:
    direnv_version: 2.35.0
    tool_deploy_list: "{{ tool_deploy_default_config_direnv }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - direnv

- name: Test role with eza
  hosts: '{{ target | default("all") }}'
  vars:
    eza_version: 0.20.16
    tool_deploy_list: "{{ tool_deploy_default_config_eza }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - eza

- name: Test role with fd
  hosts: '{{ target | default("all") }}'
  vars:
    fd_version: 10.2.0
    tool_deploy_list: "{{ tool_deploy_default_config_fd }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - fd

- name: Test role with fzf
  hosts: '{{ target | default("all") }}'
  vars:
    fzf_version: 0.57.0
    tool_deploy_list: "{{ tool_deploy_default_config_fzf }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - fzf

- name: Test role with jq
  hosts: '{{ target | default("all") }}'
  vars:
    jq_version: 1.7.1
    tool_deploy_list: "{{ tool_deploy_default_config_jq }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - jq

- name: Test role with lsd
  hosts: '{{ target | default("all") }}'
  vars:
    lsd_version: 1.1.5
    tool_deploy_list: "{{ tool_deploy_default_config_lsd }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - lsd

- name: Test role with rg
  hosts: '{{ target | default("all") }}'
  vars:
    rg_version: 14.1.1
    tool_deploy_list: "{{ tool_deploy_default_config_rg }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - rg

- name: Test role with task
  hosts: '{{ target | default("all") }}'
  vars:
    task_version: 3.40.1
    tool_deploy_list: "{{ tool_deploy_default_config_task }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - task

- name: Test role with tig
  hosts: '{{ target | default("all") }}'
  vars:
    tig_version: 2.5.11
    tool_deploy_list: "{{ tool_deploy_default_config_tig }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - tig

- name: Test role with tmux
  hosts: '{{ target | default("all") }}'
  vars:
    tmux_version: 3.5a
    tool_deploy_list: "{{ tool_deploy_default_config_tmux }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - tmux

- name: Test role with zoxide
  hosts: '{{ target | default("all") }}'
  vars:
    zoxide_version: 0.9.6
    tool_deploy_list: "{{ tool_deploy_default_config_zoxide }}"
  roles:
    - role: tool_deploy
  tags:
    - tools
    - zoxide

...
