---
# https://taskfile.dev

version: '3'

tasks:

  lint:
    cmds:
      - yamllint .
      - mdl README.md
      - ANSIBLE_CONFIG=example/ansible.cfg ansible-lint

  test:
    cmds:
      - ANSIBLE_CONFIG=example/ansible.cfg ansible-playbook example/playbook.yml

...
