---

# - name: Role tool_deploy
#   ansible.builtin.debug:
#     msg: Inside role tool_deploy

- name: Set tool deploy variables
  ansible.builtin.set_fact:
    tool_deploy_bin_path: >-
      {{ (tool_deploy_prefix | mandatory, 'bin') | ansible.builtin.path_join }}
    tool_deploy_share_path: >-
      {{ (tool_deploy_prefix | mandatory, 'share') | ansible.builtin.path_join }}
    tool_deploy_applications_path: >-
      {{ (tool_deploy_share_prefix, 'applications') | ansible.builtin.path_join }}
    tool_deploy_icons_path: >-
      {{ (tool_deploy_share_prefix, 'icons', 'hicolor', '128x128', 'apps') | ansible.builtin.path_join }}
    tool_deploy_svg_path: >-
      {{ (tool_deploy_share_prefix, 'icons', 'hicolor', 'scalable', 'apps') | ansible.builtin.path_join }}
    tool_deploy_man_path: >-
      {{ (tool_deploy_share_prefix, 'man') | ansible.builtin.path_join }}
    tool_deploy_bash_completion_path: >-
      {{ (tool_deploy_share_prefix, 'bash-completion', 'completions') | ansible.builtin.path_join }}
    tool_deploy_zsh_completion_path: >-
      {{ (tool_deploy_share_prefix, 'zsh', 'site-functions') | ansible.builtin.path_join }}

- name: Ensure directories are existing
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,go=rx
  loop:
    - "{{ tool_deploy_bin_path }}"
    - "{{ tool_deploy_applications_path }}"
    - "{{ tool_deploy_icons_path }}"
    - "{{ tool_deploy_svg_path }}"
    - "{{ (tool_deploy_man_path | mandatory, 'man1') | ansible.builtin.path_join }}"
    - "{{ (tool_deploy_man_path | mandatory, 'man5') | ansible.builtin.path_join }}"
    - "{{ (tool_deploy_man_path | mandatory, 'man7') | ansible.builtin.path_join }}"
    - "{{ (tool_deploy_man_path | mandatory, 'man8') | ansible.builtin.path_join }}"
    - "{{ tool_deploy_bash_completion_path }}"
    - "{{ tool_deploy_zsh_completion_path }}"

- name: Loop over tools
  ansible.builtin.include_tasks: main_loop.yml
  loop: "{{ tool_deploy_list | mandatory | dict2items }}"
  loop_control:
    loop_var: tool
    label: "{{ tool.key }}"

...
